enum Bread{
    PAODEFORMA="PAODEFORMA",
    PAOFRANCES="PAOFRANCES",
    PAOINTEGRAL="PAOINTEGRAL",
    PAOGERGELIM="PAOGERGELIM",
    PAODEAGUA="PAODEAGUA",
    PAODEHOTDOG="PAODEHOTDOG"
}
export default Bread;